Django/hw_project/app_auth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path("signup/", views.RegisterViews.as_view(), name="signup"),
    path(
        "signin/",
        LoginView.as_view(
            template_name="app_auth/login.html",
            form_class=LoginForm,
            redirect_authenticated_user=True,
            next_page='/'
        ),
        name="signin",
    ),
    path("logout/", views.logoutuser, name="logout"),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='app_auth/password_reset_done.html'),name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='app_auth/password_reset_confirm.html', success_url='/auth/reset-password/complete/'),name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='app_auth/password_reset_complete.html'), name='password_reset_complete'),
]

Django/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("quotes.urls")),
    path("auth/", include("app_auth.urls")),
    path("admin/", admin.site.urls)
]

Django/hw_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path("add_author/", views.add_author, name="add_author"),
    path("tag/", views.tag, name="tag"),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path("<int:page>", views.main, name="root_paginate"),
]

Django/hw_project/quotes/models.py
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.fullname

class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

Django/hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Tag, Quote, Author

class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(ModelForm):

    author = ModelChoiceField(queryset=Author.objects.all(), required=True)
    quote = CharField(min_length=10, max_length=500, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['author', 'quote']
        exclude = ['tags']

class AuthorForm(ModelForm):

    fullname = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50, required=True, widget=TextInput())
    born_location = CharField(max_length=150, required=True, widget=TextInput())
    description = CharField(required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location','description']


Django/hw_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from .forms import QuoteForm, TagForm, AuthorForm
from .models import Tag, Quote, Author
from django.contrib.auth.decorators import login_required
import logging

logger = logging.getLogger('hw_project') 

def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10 
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

@login_required
def add_quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)


            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_quote.html', {"tags": tags, 'form': form})

    return render(request, 'quotes/add_quote.html', {"tags": tags, 'form': QuoteForm()})

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)

        if form.is_valid():
            tag = form.save(commit=False)
            tag.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save(commit=False)
            new_author.save()

            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_author.html')

    return render(request, 'quotes/add_author.html', {'form': AuthorForm()})

def author_detail(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    return render(request, 'quotes/author_detail.html', {'author': author})


Django/hw_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}" style="max-width: 600px; margin: 0 auto;">
    {% csrf_token %}
    <div style="display: flex; flex-direction: column; gap: 15px;">
        <div style="display: flex; flex-direction: column;">
            <label>Author fullname:</label>
            {{ form.fullname }}
            <span style="color: red;">{{ form.errors.fullname }}</span>
        </div>
        
        <div style="display: flex; flex-direction: column;">
            <label>Born date:</label>
            {{ form.born_date }}
            <span style="color: red;">{{ form.errors.born_date }}</span>
        </div>
        
        <div style="display: flex; flex-direction: column;">
            <label>Born location:</label>
            {{ form.born_location }}
            <span style="color: red;">{{ form.errors.born_location }}</span>
        </div>
        
        <div style="display: flex; flex-direction: column;">
            <label>Description:</label>
            {{ form.description }}
            <span style="color: red;">{{ form.errors.description }}</span>
        </div>
    </div>

    <div style="display: flex; justify-content: space-between; margin-top: 20px;">
        <button type="submit" style="flex-basis: 48%;">Submit</button>
        <button type="reset" class="secondary" style="flex-basis: 48%;">Reset</button>
    </div>
</form>

{% endblock %}

Django/hw_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote'  %}" style="max-width: 600px; margin: 0 auto;">
    {% csrf_token %}
    
    <div style="display: flex; flex-direction: column; gap: 15px;">
        <div style="display: flex; flex-direction: column;">
            <label>Author fullname:</label>
            {{ form.author }}
            <span style="color: red;">{{ form.errors.author }}</span>
        </div>

        <div style="display: flex; flex-direction: column;">
            <label>Quote description:</label>
            {{ form.quote }}
            <span style="color: red;">{{ form.errors.quote }}</span>
        </div>

        <div style="display: flex; flex-direction: column;">
            <label>Select tags:</label>
            <select name="tags" multiple="multiple" required style="padding: 35px; border-radius: 5px; width: 100%;">
                {% for tag in tags %}
                    <option value="{{ tag.name }}">{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div style="display: flex; justify-content: space-between; margin-top: 20px;">
        <button type="submit" style="flex-basis: 48%;">Submit</button>
        <button type="reset" class="secondary" style="flex-basis: 48%;">Reset</button>
    </div>
</form>

{% endblock %}

Django/hw_project/quotes/templates/quotes/author_detail.html
{% extends "quotes/base.html" %}

{% block content %}
    <h1>{{ author.fullname }}</h1>
    <p><strong>Born date:</strong> {{ author.born_date }}</p>
    <p><strong>Born location:</strong> {{ author.born_location }}</p>
    <p><strong>Description:</strong> {{ author.description }}</p>

    <h2>Author quotes:</h2>
    <ul>
        {% for quote in author.quote_set.all %}
            <li>{{ quote.quote }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'quotes:root' %}">Go back</a>
{% endblock %}

Django/hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>HomeWork_10</title>
</head>

<body>

    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">New author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">New quote</a>
                    <a href="{% url 'app_auth:logout' %}" class="btn btn-primary">Logout</a>
                    {% else %}
                    <a href="{% url 'app_auth:signup' %}" class="btn btn-primary">Register</a>
                    <a href="{% url 'app_auth:signin' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>

        {% block content %} {% endblock %}

</body>

</html>

Django/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>    
                <a href="{% url 'quotes:author_detail' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
                {% endfor %}            
            </div>
        </div>

        {% endfor %}

        <nav>
            <ul class="pager">
            
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                    href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
                </li>
                
                
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                    href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
                </li>
                
            </ul>
        </nav>

    </div>
    {% endblock %}

Django/hw_project/quotes/templates/quotes/tag.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}